import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex items-center bg-white w-full justify-center">
          <section className="flex max-w-5xl w-full px-4 py-2 items-center justify-between">
            <div className="w-32 h-8 relative">
              <Image
                src="/logo.png"
                alt="Logo"
                width={134}
                height={27}
                className="absolute w-full h-full object-contain"
              />
            </div>
          </section>
        </header>
        {children}
      </body>
    </html>
  );
}
